### ISSUE TITLE
手动指定证书情况可能需要把auto_https禁用

### ISSUE THREAD

**Issue by sola97** [RayWangQvQ/naiveproxy-docker#1]
我这手动指定了的是泛域名证书，caddy默认会不停的去申请证书，目前我是整个禁用了
{
  auto_https off
}

**Comment by RayWangQvQ** [comment]
查了下文档

auto_https🔗

Configure automatic HTTPS. There are a few modes to choose from:

off: Disabled entirely. No certificate management or redirects.

disable_redirects: Disable only HTTP-to-HTTPS redirects.

disable_certs: Disable only certificate automation.

ignore_loaded_certs: Automate certificates even for names which appear on manually-loaded certificates

使用现有证书时，确实off比较好，或者disable_certs

稍后我来更新下，感谢反馈

**Comment by RayWangQvQ** [comment]
已修复
